name: CI Build and Deploy

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specify the type of runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set the Node.js version

    - name: Install Dependencies
      run: npm install  # Install npm dependencies

    - name: Set Execution Permissions for WDIO
      run: chmod +x node_modules/.bin/wdio

    - name: Run WebdriverIO Tests
      run: npx wdio run wdio.chrome.conf.js  # Run tests

    - name: Install Google Chrome  # This step is optional, depends on your testing setup
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Deploy to GitHub Pages
      run: |
        git checkout --orphan gh-pages
        git reset --hard
        git commit --allow-empty -m "Initializing gh-pages branch"
        git push --force origin gh-pages  # Force push to overwrite remote branch
        cp -r ../allure-report/* .   # Make sure this path is correct; Copy new Allure report files
        git add .
        git commit -m "Deploy Allure report to gh-pages"  # Commit the new report
        git push origin gh-pages  # Force push the update

    
    - name: Clean up Post-build
      if: always()  
      run: |
        git checkout master
        git branch -D gh-pages  # Delete the local gh-pages branch

