name: Run WebdriverIO Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install dependencies
      run: npm install
    - name: Set Execution Permissions for WDIO
      run: chmod +x node_modules/.bin/wdio
    - name: Run tests
      run: npx wdio run wdio.conf.js
    - name: Publish Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.WD_SECRET_PAGE }}
        publish_dir: ./allure-report
        
