name: Generate and Publish Allure Report

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Important to fetch all history for versioning and CI management

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Or any version that matches your project requirements

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate Allure results
      run: npm run test  # Your test script should configure Allure to output results

    - name: Install Allure Command Line
      run: sudo apt-get install allure -y

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: Copy Allure Report to root
      run: |
        rm -rf *  # Clears the gh-pages branch
        cp -r ../allure-report/* .  # Assumes working directory is still where allure-report was generated

    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Deploy Allure Report" -a || echo "No changes to commit"
        git push origin gh-pages

